#name: Task Manager App CI Pipeline

#on: [push, pull_request]

#jobs: 
  # hello-world:
  #   name: Hello world
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Say hello
  #       run: echo "Hello from GitHub Actions!"

  #     - name: Show environment
  #       run: |
  #         echo "Running on: $(uname -a)"
  #         echo "Node version: $(node --version)"
  #         echo "Branch: ${{ github.ref }}"